<?php
/**
 * WP Distraction Free View | Frontend Helpers.
 *
 * @package WordPress
 * @subpackage WP Distraction Free View
 * @since 1.0.0
 */

namespace WPDFV\Includes;

// Bailout, if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Helpers {
	/**
	 * Whether automatic button injection is temporarily suspended.
	 *
	 * @since 2.0.0
	 *
	 * @var bool
	 */
	private static $suspend_button_injection = false;

	/**
	 * This helper function is used to display read mode button.
	 *
	 * @param int    $id                 Post ID.
	 * @param string $button_text        Optional button text override.
	 * @param string $wrapper_attributes Optional wrapper attributes.
	 *
	 * @since  1.4.2
	 * @access public
	 *
	 * @return mixed
	 */
	public static function display_read_mode_button( $id = 0, $button_text = '', $wrapper_attributes = '' ) {
		// If `$id` is `0`, then get it from `$post` global variable.
		if ( 0 === $id ) {
			global $post;
			if ( ! $post instanceof \WP_Post ) {
				return '';
			}
			$id = $post->ID;
		}

		$id       = absint( $id );
		$btn_text = '' !== $button_text ? sanitize_text_field( $button_text ) : self::get_button_text();

		if ( ! $id ) {
			return '';
		}

		$wrapper_attributes = '' !== $wrapper_attributes ? $wrapper_attributes : 'class="wpdfv-fullscreen-container"';

		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Wrapper attributes are either static or generated by get_block_wrapper_attributes().
		return sprintf(
			'<div %3$s><button type="button" class="wpdfv-fullscreen-btn wpdfv-reader-toggle" data-post-id="%1$s" aria-haspopup="dialog" aria-label="%2$s">%2$s</button></div>',
			esc_attr( $id ),
			esc_html( $btn_text ),
			$wrapper_attributes
		);
	}

	/**
	 * This function is used to get default button text.
	 *
	 * @since  1.4.2
	 * @access public
	 *
	 * @return string
	 */
	public static function get_button_text() {
		$default_text = self::get_default_button_text();
		$settings     = self::get_settings();

		return ! empty( $settings['button_text'] ) ? sanitize_text_field( $settings['button_text'] ) : $default_text;
	}

	/**
	 * Get the value of a settings field
	 *
	 * @param string $option  settings field name.
	 * @param string $section the section name this field belongs to.
	 * @param string $default_value Default text if it's not found.
	 *
	 * @since  1.4.2
	 * @access public
	 *
	 * @return string
	 */
	public static function get_option( $option, $section, $default_value = '' ) {
		$section = "wpdfv_{$section}";
		$options = get_option( $section );

		if ( isset( $options[ $option ] ) ) {
			return $options[ $option ];
		}

		return $default_value;
	}

	/**
	 * This helper function is used to display read mode button at.
	 *
	 * @since  1.6.0
	 * @access public
	 *
	 * @return string
	 */
	public static function display_location() {
		return Reader::display_location();
	}

	/**
	 * Check whether automatic frontend button injection is enabled.
	 *
	 * @since 2.1.0
	 *
	 * @return bool
	 */
	public static function is_automatic_button_enabled() {
		return Reader::is_automatic_button_enabled();
	}

	/**
	 * Get Settings.
	 *
	 * @since  1.6.0
	 * @access public
	 *
	 * @return array
	 */
	public static function get_settings() {
		return Reader::get_settings();
	}

	/**
	 * Get default button text.
	 *
	 * @since  1.6.0
	 * @access public
	 *
	 * @return string
	 */
	public static function get_default_button_text() {
		return Reader::get_default_button_text();
	}

	/**
	 * Where to display?
	 *
	 * @since  1.6.0
	 * @access public
	 *
	 * @return array
	 */
	public static function where_to_display() {
		return Reader::where_to_display();
	}

	/**
	 * Check whether automatic button injection is suspended.
	 *
	 * @since 2.0.0
	 *
	 * @return bool
	 */
	public static function is_button_injection_suspended() {
		return self::$suspend_button_injection;
	}

	/**
	 * Run a callback while automatic button injection is suspended.
	 *
	 * @since 2.0.0
	 *
	 * @param callable $callback Callback to run.
	 *
	 * @return mixed
	 */
	public static function without_button_injection( callable $callback ) {
		$previous_state                 = self::$suspend_button_injection;
		self::$suspend_button_injection = true;

		try {
			return $callback();
		} finally {
			self::$suspend_button_injection = $previous_state;
		}
	}
}
