# These are supported funding model platforms

github: mehul0810
patreon: mehulgohil
ko_fi: mehulgohil
custom: ['https://mehulgohil.com/donations/buy-me-a-cup-of-coffee/?utm_medium=plugin&utm_source=wpdfv&utm_campaign=sponsor']
