name: Build & Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: WP Distraction Free View
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: wp-distraction-free-view
